language: java
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - git clone git://github.com/ome/ice-builder-gradle
  - cd ice-builder-gradle && ./gradlew publishToMavenLocal
  - cd ..
  - git clone git://github.com/ome/omero-dsl-plugin
  - cd omero-dsl-plugin && ./gradlew publishToMavenLocal
  - cd ..
  - git clone git://github.com/ome/omero-model
  - cd omero-model && ./gradlew publishToMavenLocal
  - cd ..
  - git clone git://github.com/ome/omero-common
  - cd omero-common && ./gradlew publishToMavenLocal
  - cd ..
  - git clone git://github.com/ome/omero-romio
  - cd omero-romio && ./gradlew publishToMavenLocal
  - cd ..
  - git clone git://github.com/ome/omero-renderer
  - cd omero-renderer && ./gradlew publishToMavenLocal
  - cd ..
script:
  - ./gradlew publishToMavenLocal

deploy:
  provider: script
  script: ./gradlew publish
  skip_cleanup: true
  on:
    branch: deploy