language: java

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
  - sudo apt-add-repository "deb http://zeroc.com/download/apt/ubuntu14.04 stable main"
  - sudo apt-get update -q
  - sudo apt-get install libzeroc-ice-java -y

install:
  - DIR=$PWD; (cd /tmp; gradle wrapper --gradle-version=5.2.1; mv .gradle gradle gradlew $DIR)

script:
  - ./gradlew publishToMavenLocal
